### Welcome Endpoint
# Prueba de conexión básica para verificar si el servidor responde
GET http://localhost:8080/api
Accept: application/json

### Error Endpoint
# Prueba de conexión básica para verificar si el servidor responde
GET http://localhost:8080/api/error
Accept: application/json